package ch.uzh.csg.nfclib;

//TODO: javadoc
public enum NfcEvent {
	INIT_FAILED,
	INITIALIZED,
	COMMUNICATION_ERROR,
	ERROR_REPORTED,
	MESSAGE_SENT,
	MESSAGE_RECEIVED,
	MESSAGE_RETURNED,
	CONNECTION_LOST;
}
